# Generated by Django 2.0.3 on 2018-04-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0002_auto_20180417_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='replyed',
            field=models.BooleanField(default=False),
        ),
    ]
