# Generated by Django 2.0.3 on 2018-04-17 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0003_contact_replyed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='replyed',
            new_name='replayed',
        ),
    ]
