# Generated by Django 2.0.3 on 2018-04-04 23:36

from django.db import migrations, models

import services.models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=services.models.upload_location),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
