# Generated by Django 2.0.3 on 2018-04-04 23:54

import django.db.models.deletion
from django.db import migrations, models

import services.models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0002_auto_20180405_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_title', models.CharField(max_length=200)),
                ('ar_title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('en_body', models.TextField(blank=True, null=True)),
                ('ar_body', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=services.models.upload_location)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts',
                                              to='services.Service')),
            ],
        ),
    ]
