# Generated by Django 2.0.3 on 2018-04-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0003_servicepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='publish_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
