# Generated by Django 2.0.3 on 2018-04-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0005_serviceprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
