# Generated by Django 2.0.3 on 2018-04-06 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0006_serviceprice_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprice',
            old_name='ar_title',
            new_name='ar_price_title',
        ),
        migrations.RenameField(
            model_name='serviceprice',
            old_name='en_title',
            new_name='en_price_title',
        ),
    ]
