# Generated by Django 2.0.3 on 2018-04-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0007_auto_20180406_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='publish_on_pricing',
            field=models.BooleanField(default=False),
        ),
    ]
