# Generated by Django 2.0.3 on 2018-04-08 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0008_service_publish_on_pricing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='publish_on_pricing',
            new_name='publish_pricing',
        ),
    ]
