# Generated by Django 2.0.3 on 2018-04-19 16:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20180419_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='ar_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='en_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='ar_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='en_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
