# Generated by Django 2.0.3 on 2018-04-19 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20180419_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('comment_text', models.TextField()),
                ('service_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='services.ServicePost')),
            ],
        ),
    ]
