# Generated by Django 2.0.3 on 2018-04-19 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_servicepostcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepostcomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicepostcomment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
