# Generated by Django 2.0.3 on 2018-04-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20180420_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepostcomment',
            old_name='comment_text',
            new_name='comment',
        ),
    ]
