# Generated by Django 2.0.3 on 2018-04-20 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_serviceclient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceclient',
            old_name='ar_name',
            new_name='ar_client_name',
        ),
        migrations.RenameField(
            model_name='serviceclient',
            old_name='en_name',
            new_name='en_client_name',
        ),
    ]
