# Generated by Django 2.0.3 on 2018-04-20 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20180420_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceclient',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
